### ISSUE TITLE
Press Query Urgent

### ISSUE THREAD

**Issue by jonese1** [top-poop/top-of-the-poops#10]
Hello,

We're looking to publish a story in the next few days and want to clarify which river No. 20 is on the worst polluted rivers list?

Is it The River Taff/Taf  that runs through Cardiff or the Taf that runs through West Wales

Thanks

**Comment by top-poop** [comment]
Hi - Thanks for the interest in our site.
It would be great to hear more about your story - email us at press [at] top-of-the-poops.org

You ask a good question. Unfortunately, it is difficult to give a precise answer. Currently the England EA does not use 'waterbody ids' in their information, so we can't use that to definitively identify a waterbody, so we have to go only by name. The naming information in these files has been quite erratic.

However,  in this particular case, all the records that are for the "River Taff" come from the Cardiff / Pontypridd / Merthyr Tydfil area, and feed into the River Taff.

Here for your reference are those CSOs, in descending order of severity

```
Rhydfelin CSO  Off Lionel Terrace,CF37 5RF
Settled Storm at Cynon Valley Wastewater Treatment Works,CF37 3ND
"Tonteg Road, Upper Boat CSO and Pumping Station Emergency Overflow",CF37 5BH
Cilfynydd STW  Cilfynydd  Pontypridd Settled Storm,CF37 4WX
Tongwynlais CSO,CF15 7NJ
Abercynon Wood Rd SPS,CF45 4RP
A CSO AT JACKSONS BRIDGE,CF47 8PS
"Crossbrook St CSO, Pontypridd",CF37 4TD
CSO  COLLEGE CAR PK  MERTHYR TYDFIL,CF48 1AR
Merthyr Tydfil Georgetown Lines Bridge CSO,CF47 8PD
"Gellideg Tai Mawr Rd CSO, Merthyr Tydfil",CF48 1LF
"Phyllis Street CSO, Troedyrhiw",CF48 4JW
"CSO Avenue De Clichy, Merthyr",CF47 8HB
YNYSANGHARAD PARK CSO,CF37 4SS
"Quakers Yard CSO, Greenfield Victoria Bridge",CF46 5EG
"Quakers Yard CSO, Fiddlers Elbow St, Cynon",CF46 5EA
Cardiff Wood St/Havelock St Jn CSO,CF10 1ET
"Troedyrhiw, Yew Street CSO",CF48 4EB
3rd Trunk CSO South of Glan Yr Afon,CF48 4PZ
TROEDYRHIW PS,CF48 4LL
Park Street PS,CF10 1XR
"Taff St CSO, Pontypridd",CF37 2SU

```

It is great that you are covering this story. Please ensure to give suitable attribution to our site - with a link to top-of-the-poops.org - as our content is CC-BY-SA 4.0 - Sorry to mention this, but a few media outlets have forgotten about this recently.

Please do let us know about the article when it goes live.

Cheers!
