### ISSUE TITLE
Accuracy of Information

### ISSUE THREAD

**Issue by DavidGEntwistle** [top-poop/top-of-the-poops#16]
Hi, 

Good work on the web site. I generally support what you are aiming to do, but have some questions and possible concerns about the validity of the data.  I've seen the warning you give.

We have a local press report regarding a "cocktail of filth dumped into seas". I believe it is based on ToTPs information. It lists the 10 worst North Wales beaches for sewage spills in 2022. Morfa Nefyn, close to where I live is listed as number 2 with 521 spills and 1571 hours total duration.

I assume this is related to information provided here by Dwr Cymru (Welsh Water):

https://corporate.dwrcymru.com/en/community/environment/combined-storm-overflows

A couple of questions... 

When you refer to a beach, I assume you are using the water companies catchment area designation, and not actually the beach. Is that correct? In our case the waste water overflow discharges will be in areas east and west of Morfa Nefyn beach and not actually associated with Morfa Nefyn beach.

Adding all the hours of overflow, for all the facilities in the catchment, I see where the total hours come from. The bulk of the overflows are associated with a WWTW in this area. This is serving the small local community. I agree overflows are not good, but an overflow from a small treatment works is a lot less volume than an overflow from from a large treatment works serving a larger population. 

Consequently, I think the press article gives Morfa Nefyn beach a bit of an undeserved label. The bathing water quality is assessed by Natural resources Wales and is assessed as excellent.

https://environment.data.gov.uk/wales/bathing-waters/profiles/

Is there any way any of this could be addressed to be provide more representative information?

**Comment by top-poop** [comment]
Hi. Thanks for your interest. We report on the data supplied by the water companies. There is a set of sewage outlets that the water companies and the environment agency agree will affect a given designated beach, and we show the totals for these.
We don't have any involvement with the selection or modelling of impact for these.
If you feel they are unrepresentative, it's more the water companies or EAs domain.
Of course, nobody wants to have their local area designated as being affected by sewage, but the best way for this to happen would simply be for the water companies not to release it.
Water quality sampling is very inexact, as often the samples are taken specifically at times when the samplers know there will be low pollution.
We don't intend to make any changes to the data, except where we have made any error in our interpretation of the EDM data, which I dont think we have, in this case.

**Comment by DavidGEntwistle** [comment]
The information ToTPs provide for the adjacent Abersoch catchment lists 0 hours, whereas the Dwr Cymru asset MYNYTHO STW - STORM OVERFLOW, within this catchment area, lists 640.25 hours of discharge in 2022, on the following web site:

https://corporate.dwrcymru.com/en/community/environment/combined-storm-overflows

Possibly an error there?
