### ISSUE TITLE
Just Getting In Touch

### ISSUE THREAD

**Issue by AmySlack** [top-poop/top-of-the-poops#4]
Hi!

Apologies for logging an issue when I actually just want to get in touch - I am not sure how to use this site so not quite sure how to message you!

My name is Amy Slack and I am Head of Campaigns & Policy at Surfers Against Sewage. As you may be awear, we have been campaigning on the issue of sewage pollution for over 30 years and now lead a coalition of organisations and community groups called the #EndSewagePollution coalition who have come together over the last 18 months to drive the agenda with the public and with politicians, particularly through the Environment Act. 

The reason for getting in touch is mainly to connect with you. 'Top of the Poops' is a great website and we love it here at Surfers Against Sewage! It would be great to have an informal chat with you and to introduce ourselves more than anything. It would be great to understand your plans for this site going forward and to share our campaign plans a bit with you.

You can reach me directly on xxx  *private information redacted by top-poop*

Look forward to talking!

Many thanks

Amy

**Comment by top-poop** [comment]
Thanks so much for your supportive comments!
