### ISSUE TITLE
Constituency data fails to download

### ISSUE THREAD

**Issue by V2G-EVSE** [top-poop/top-of-the-poops#9]
Never having used Node before I had to install a long list of undocumented stuff I've never previously heard of. Eventually make seemed to work, however...

When it came to download the constituency data the install ground to a halt. It seems the location of said data has changed?

Jim

**Comment by time4tea** [comment]
Hi - as much as I would love everyone to be able to access this information, it is true that some things move around. I can't really support the software, it is open really for transparency.

If you had a specific issue that you wanted to address (other than can't find the data) I'd be very happy to look into it.

In particular, lots of the urls of data sources seem to change a lot, which is contrary to government guidelines, so every do often we have to hunt the Internet and track them down again.

https://www.w3.org/Provider/Style/URI
https://gcs.civilservice.gov.uk/blog/link-shorteners-the-long-and-short-of-why-you-shouldnt-use-them/

**Comment by top-poop** [comment]
Hi - as much as I would love everyone to be able to access this information, it is true that some things move around. I can't really support the software, it is open really for transparency.

If you had a specific issue that you wanted to address (other than can't find the data) I'd be very happy to look into it.

In particular, lots of the urls of data sources seem to change a lot, which is contrary to government guidelines, so every do often we have to hunt the Internet and track them down again.

https://www.w3.org/Provider/Style/URI
https://gcs.civilservice.gov.uk/blog/link-shorteners-the-long-and-short-of-why-you-shouldnt-use-them/

**Comment by V2G-EVSE** [comment]
I can find the data, but whether it's still in the format you expect I cannot say as yet. I've no idea when it moved.

Your main site says "If you find something that is incorrect, please raise an issue at the GitHub issues and we'll endeavour to fix it quickly", so I did as suggested!

The specific issue that caused me to come here can be summarised as follows:

[https://twitter.com/jim_hunt/status/1627105743966031872](https://twitter.com/jim_hunt/status/1627105743966031872)

What is the reason for the alleged "Unknown River" in South West England?

![TOTP-SWW-2021](https://user-images.githubusercontent.com/65675558/219977168-ad98b31f-2b59-4164-babc-5f06e5ea1e61.jpg)

**Comment by top-poop** [comment]
Hi -
There is a very simple explanation for this. The consent information, as linked in the README - "Consented Discharges with Conditions" - contains permit information for each water company. The permits for south west water list the "receiving water" as "Unknown" for 51 sites, for the consents for 2021. 

Although "Unknown" clearly isn't a single river - it is indicative that South West Water and the Environment Agency haven't bothered to record where the sewage is going.

**Comment by V2G-EVSE** [comment]
Thanks for the eminently understandable explanation.

Now to discover what South West Water's explanation is...

Jim

**Comment by top-poop** [comment]
You are welcome - I wish you luck - I'd appreciate if you could let us know how you get on, or any people you found that were useful to contact.
